import type { Metadata } from "next";
import { Poppins, Lato } from "next/font/google";
import "./globals.css";

// Poppins as primary, Lato as fallback
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-lato",
  display: "swap",
});

export const metadata: Metadata = {
  title: "UpPumps",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${lato.variable} font-sans antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
